services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: population
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  get_data:
    build: .
    command: python main.py
    depends_on:
      - db
    env_file:
      - .env

  print_data:
    build: .
    command: python main.py print
    depends_on:
      - db
    env_file:
      - .env

volumes:
  pg_data:
